### ISSUE TITLE
Protected message not working

### ISSUE THREAD

**Issue by kaohlive** [kaohlive/com.xbox.smartglass#1]
The discover simple message is working properly.
I have (I think) implemented all the code to send the connect message (anonymous right now) and with all the secrets and encryptions etc.
However I can not get a response from the console. So without debugging on the console or a answer on what is failing it is now unclear to me what I am doing wrong.

Any help is greatly appreciated.

**Comment by tuxuser** [comment]
1. How is the PKCS7 padding working in your lib?
https://github.com/kaohlive/com.xbox.smartglass/blob/master/lib/SmartGlass/glasscryptokeys.js#L27
If you pass it an array of 16 bytes - will it add another 16 bytes or padding? If so - thats wrong.
SmartGlass uses a custom form of PKCS7 you could say - if the bytes to pad are equal to 16 bytes it wont add padding!

2. Is this the correct format of public key?
https://github.com/kaohlive/com.xbox.smartglass/blob/master/lib/SmartGlass/glasscryptokeys.js#L27
You want to have an uncompressed point value, as bytes. Can you verify that?

3. In anonymous connect requests there is no need to segment aka. fragment the packet.
https://github.com/kaohlive/com.xbox.smartglass/blob/master/lib/SmartGlass/glasscryptokeys.js#L27

4. It might be as simple as that to fix:
```
Protected Payload Length
The protected payload length inside the header indicates the data length without padding.
```

Padding: https://openxbox.org/smartglass-documentation/cryptography/#padding
Crypto: https://openxbox.org/smartglass-documentation/cryptography/#cryptography
Connect Request: https://openxbox.org/smartglass-documentation/simple_message/#connect-request

Maybe this one helps in your journey:
https://github.com/OpenXbox/xbox-smartglass-core-node

**Comment by kaohlive** [comment]
Thank you for these pointers, I will investigate those. But the other node.js project is a real find. I completely missed that in my search before. For my homey plugin project ill give that one a try first. 
But for my attempt to write it myself I can do some more investigation, thanks for the effort! Really appreciated

**Comment by kaohlive** [comment]
I used the npm package for the homey implementation, and its near perfect. So ill rest this issue
